# Generated by Django 3.1.1 on 2021-01-03 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(blank=True, max_length=200)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 3, 21, 9, 25, 964170))),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
